//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int Id { get; set; }
        public string Model_size { get; set; }
        public string Price_topup { get; set; }
    }
}
