//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infor
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Image_Order { get; set; }
        public string Image_Product { get; set; }
        public string Model_size { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string Address { get; set; }
    }
}
